try:
    print(x)
    
except:
    print("Something went wrong")
finally: 
    print("They 'try except' is finished")
